import type { Metadata } from "next";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import "./css/globals.css";
import NavBar from "./components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="header-container">
          <div className="header">
            <div className="logo-container">
              <Image
                width={20}
                height={20}
                className="logo-img"
                src="/insight_3.webp"
                alt="logo"
              />
              <p className="logo-name">PANZERFAUST</p>
            </div>

            <NavBar />

            <a className="collab-butt">Work with Me!</a>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
